// Mock products — replaces backend for now
// Each product has BOTH retail (B2C) and wholesale (B2B) prices

export const mockProducts = [
  {
    _id: '1',
    name: 'Fresh Tomatoes',
    category: 'Vegetables',
    image: '🍅',
    seller: 'Ramesh Sabzi Wala',
    sellerType: 'Street Vendor',
    location: 'Sonipat, Haryana',
    retailPrice: 40,
    wholesalePrice: 22,
    unit: 'per kg',
    minB2BQty: 10,
    rating: 4.5,
    inStock: true,
  },
  {
    _id: '2',
    name: 'Basmati Rice (Premium)',
    category: 'Grains',
    image: '🍚',
    seller: 'Sharma Wholesale',
    sellerType: 'Wholesaler',
    location: 'Karnal, Haryana',
    retailPrice: 180,
    wholesalePrice: 120,
    unit: 'per kg',
    minB2BQty: 25,
    rating: 4.7,
    inStock: true,
  },
  {
    _id: '3',
    name: 'Cotton T-Shirt',
    category: 'Clothing',
    image: '👕',
    seller: 'StreetWear India',
    sellerType: 'Local Seller',
    location: 'Delhi',
    retailPrice: 299,
    wholesalePrice: 149,
    unit: 'per piece',
    minB2BQty: 50,
    rating: 4.2,
    inStock: true,
  },
  {
    _id: '4',
    name: 'Wireless Earbuds',
    category: 'Electronics',
    image: '🎧',
    seller: 'TechHub Distributors',
    sellerType: 'Distributor',
    location: 'Gurgaon',
    retailPrice: 1499,
    wholesalePrice: 899,
    unit: 'per piece',
    minB2BQty: 20,
    rating: 4.4,
    inStock: true,
  },
  {
    _id: '5',
    name: 'Aloo (Potatoes)',
    category: 'Vegetables',
    image: '🥔',
    seller: 'Kishan Kirana',
    sellerType: 'Local Kirana',
    location: 'Sonipat, Haryana',
    retailPrice: 30,
    wholesalePrice: 18,
    unit: 'per kg',
    minB2BQty: 20,
    rating: 4.3,
    inStock: true,
  },
  {
    _id: '6',
    name: 'Home Tiffin Service',
    category: 'Food',
    image: '🍱',
    seller: 'Geeta Aunty Tiffins',
    sellerType: 'Tiffin Service',
    location: 'Delhi',
    retailPrice: 90,
    wholesalePrice: 70,
    unit: 'per meal',
    minB2BQty: 15,
    rating: 4.8,
    inStock: true,
  },
  {
    _id: '7',
    name: 'Steel Water Bottle',
    category: 'Home & Kitchen',
    image: '🍶',
    seller: 'Modern Steel Co.',
    sellerType: 'Wholesaler',
    location: 'Mumbai',
    retailPrice: 449,
    wholesalePrice: 220,
    unit: 'per piece',
    minB2BQty: 30,
    rating: 4.6,
    inStock: true,
  },
  {
    _id: '8',
    name: 'Custom Stitched Kurta',
    category: 'Clothing',
    image: '👘',
    seller: 'Babu Tailor',
    sellerType: 'Street Tailor',
    location: 'Sonipat, Haryana',
    retailPrice: 650,
    wholesalePrice: 400,
    unit: 'per piece',
    minB2BQty: 10,
    rating: 4.5,
    inStock: false,
  },
  {
    _id: '9',
    name: 'Onions',
    category: 'Vegetables',
    image: '🧅',
    seller: 'Ramesh Sabzi Wala',
    sellerType: 'Street Vendor',
    location: 'Sonipat, Haryana',
    retailPrice: 35,
    wholesalePrice: 20,
    unit: 'per kg',
    minB2BQty: 15,
    rating: 4.4,
    inStock: true,
  },
  {
    _id: '10',
    name: 'LED Bulb 9W',
    category: 'Electronics',
    image: '💡',
    seller: 'Bright Electricals',
    sellerType: 'Distributor',
    location: 'Faridabad',
    retailPrice: 150,
    wholesalePrice: 75,
    unit: 'per piece',
    minB2BQty: 50,
    rating: 4.5,
    inStock: true,
  },
  {
    _id: '11',
    name: 'Atta (Wheat Flour)',
    category: 'Grains',
    image: '🌾',
    seller: 'Sharma Wholesale',
    sellerType: 'Wholesaler',
    location: 'Karnal, Haryana',
    retailPrice: 55,
    wholesalePrice: 38,
    unit: 'per kg',
    minB2BQty: 50,
    rating: 4.7,
    inStock: true,
  },
  {
    _id: '12',
    name: 'Phone Cover (Universal)',
    category: 'Electronics',
    image: '📱',
    seller: 'Mobile Bazaar',
    sellerType: 'Local Seller',
    location: 'Delhi',
    retailPrice: 199,
    wholesalePrice: 80,
    unit: 'per piece',
    minB2BQty: 100,
    rating: 4.0,
    inStock: true,
  },
];

export const categories = [
  { name: 'All', emoji: '🛒' },
  { name: 'Vegetables', emoji: '🥬' },
  { name: 'Grains', emoji: '🌾' },
  { name: 'Clothing', emoji: '👕' },
  { name: 'Electronics', emoji: '📱' },
  { name: 'Home & Kitchen', emoji: '🍶' },
  { name: 'Food', emoji: '🍱' },
];